export enum SpaceType {
    BEDROOM = 'BEDROOM',
    OFFICE = 'OFFICE',
    CLASSROOM = 'CLASSROOM',
    MEETING_ROOM = 'MEETING_ROOM',
    LABORATORY = 'LABORATORY',
    CAFETERIA = 'CAFETERIA',
    BATHROOM = 'BATHROOM',
    STORAGE = 'STORAGE',
    HALLWAY = 'HALLWAY',
    OTHER = 'OTHER',
}