import { Injectable, Logger } from '@nestjs/common';
import { RabbitSubscribe } from '@golevelup/nestjs-rabbitmq';
import { EmailService } from '../services/email.service';

interface UserCreatedData {
    userId: string;
    email: string;
    firstName: string;
    lastName: string;
    role: string;
    temporaryPassword: string;
    passwordEncrypted: string;
    status: string;
    emailVerified: boolean;
}

interface UserCreatedEvent {
    eventId: string;
    eventType: string;
    timestamp: string;
    version: string;
    data: UserCreatedData;
}

/**
 * Handler pour l'événement user.created
 * Envoie un email de bienvenue avec le mot de passe temporaire
 */
@Injectable()
export class UserCreatedHandler {
    private readonly logger = new Logger(UserCreatedHandler.name);

    constructor(private readonly emailService: EmailService) {}

    /**
     * Écoute les événements user.created depuis RabbitMQ
     */
    @RabbitSubscribe({
        exchange: 'user-domain-events',
        routingKey: 'user.created',
        queue: 'auth-service.user-created',
        queueOptions: {
            durable: true,
        },
    })
    async handleUserCreated(event: UserCreatedEvent): Promise<void> {
        try {
            const { data } = event;

            this.logger.log(`📧 Handling user.created event for: ${data.email}`);
            this.logger.log(`Event ID: ${event.eventId}, Type: ${event.eventType}`);

            // Envoyer l'email de bienvenue avec le mot de passe
            await this.emailService.sendAutoGeneratedPassword(
                data.email,
                data.firstName,
                data.lastName,
                data.temporaryPassword,
                data.role,
            );

            this.logger.log(`✅ Welcome email sent successfully to: ${data.email}`);
        } catch (error) {
            this.logger.error(`❌ Failed to send email to ${event?.data?.email || 'unknown'}:`, error);
            // Ne pas bloquer le flux même si l'email échoue
        }
    }
}
