// src/application/services/email.service.ts

import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import * as nodemailer from 'nodemailer';
import { Transporter } from 'nodemailer';

@Injectable()
export class EmailService {
  private readonly logger = new Logger(EmailService.name);
  private transporter: Transporter | null = null;
  private smtpEnabled: boolean;

  constructor(private readonly configService: ConfigService) {
    this.smtpEnabled = this.configService.get<string>('SMTP_ENABLED') === 'true';

    if (this.smtpEnabled) {
      try {
        this.transporter = nodemailer.createTransport({
          host: this.configService.get<string>('SMTP_HOST'),
          port: this.configService.get<number>('SMTP_PORT'),
          secure: this.configService.get<string>('SMTP_SECURE') === 'true',
          auth: {
            user: this.configService.get<string>('SMTP_USER'),
            pass: this.configService.get<string>('SMTP_PASS'),
          },
          debug: true,
          logger: true,
        });

        this.logger.log('SMTP Transporter initialized');
        this.verifyConnection();
      } catch (error) {
        this.logger.error('Failed to initialize SMTP transporter:', error);
        this.smtpEnabled = false;
      }
    } else {
      this.logger.warn('SMTP is disabled. Emails will be logged only.');
    }
  }

  private async verifyConnection(): Promise<void> {
    if (!this.transporter) return;

    try {
      await this.transporter.verify();
      this.logger.log('SMTP connection verified');
    } catch (error) {
      this.logger.error('SMTP connection verification failed:', error.message);
      this.smtpEnabled = false;
    }
  }

  async sendVerificationCode(
    email: string,
    firstName: string,
    code: string,
  ): Promise<void> {
    const subject = 'Vérification de votre adresse email - IMMO360';
    const html = this.generateVerificationCodeEmail(firstName, code);

    if (this.smtpEnabled && this.transporter) {
      await this.sendEmail(email, subject, html);
    } else {
      this.logger.warn(`SMTP disabled - Email would be sent to: ${email}`);
    }
  }

  async sendAutoGeneratedPassword(
    email: string,
    firstName: string,
    lastName: string,
    plainPassword: string,
    role: string,
  ): Promise<void> {
    const subject = 'Vos identifiants de connexion - IMMO360';
    const html = this.generatePasswordEmail(firstName, lastName, email, plainPassword, role);

    if (this.smtpEnabled && this.transporter) {
      await this.sendEmail(email, subject, html);
    } else {
      this.logger.warn(`SMTP disabled - Email would be sent to: ${email}`);
    }
  }

  private async sendEmail(to: string, subject: string, html: string): Promise<void> {
    if (!this.transporter) {
      throw new Error('SMTP transporter not initialized');
    }

    try {
      const info = await this.transporter.sendMail({
        from: `"IMMO360" <${this.configService.get<string>('SMTP_FROM')}>`,
        to,
        subject,
        html,
      });

      this.logger.log(`Email sent to ${to}`);
      this.logger.log(`Message ID: ${info.messageId}`);
    } catch (error) {
      this.logger.error(`Failed to send email to ${to}: ${error.message}`);
      throw new Error(`Failed to send email: ${error.message}`);
    }
  }

  /**
   * TEMPLATE EMAIL — CODE DE VÉRIFICATION
   */
  private generateVerificationCodeEmail(firstName: string, code: string): string {
    return `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8" />
          <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #1f2937; background-color: #f3f4f6; margin: 0; padding: 0; }
            .container { max-width: 600px; margin: 40px auto; background-color: white; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.05); overflow: hidden; }
            .header { background-color: #1e3a8a; color: white; padding: 30px; text-align: center; }
            .header h1 { margin: 0; font-size: 22px; letter-spacing: 0.5px; }
            .content { padding: 30px; }
            h2 { font-size: 20px; margin-top: 0; color: #111827; }
            .intro { margin-bottom: 25px; }
            .code-box { background-color: #f9fafb; border: 2px solid #1e3a8a; padding: 20px; text-align: center; font-size: 32px; font-weight: bold; letter-spacing: 8px; border-radius: 6px; color: #1e3a8a; margin: 25px 0; }
            .info { font-size: 15px; color: #4b5563; }
            .footer { text-align: center; font-size: 12px; color: #6b7280; padding: 25px; background-color: #f9fafb; margin-top: 20px; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1>IMMO360 — Vérification de l'adresse email</h1>
            </div>
            <div class="content">
              <h2>Bonjour ${firstName},</h2>
              <p class="intro">
                Merci d'avoir créé un compte sur IMMO360.<br />
                Pour finaliser votre inscription, veuillez saisir le code ci-dessous :
              </p>

              <div class="code-box">${code}</div>

              <p class="info">
                Ce code expirera dans 24 heures.<br />
                Si vous n'êtes pas à l'origine de cette demande, vous pouvez ignorer ce message.
              </p>
            </div>
            <div class="footer">
              IMMO360 — Gestion Intelligente des Infrastructures<br />
              Ce message est automatique.
            </div>
          </div>
        </body>
      </html>
    `;
  }

  /**
   * TEMPLATE EMAIL — MOT DE PASSE TEMPORAIRE
   */
  private generatePasswordEmail(
    firstName: string,
    lastName: string,
    email: string,
    plainPassword: string,
    role: string,
  ): string {
    return `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8" />
          <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #1f2937; background-color: #f3f4f6; margin: 0; padding: 0; }
            .container { max-width: 600px; margin: 40px auto; background-color: white; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.05); overflow: hidden; }
            .header { background-color: #1e3a8a; color: white; padding: 30px; text-align: center; }
            .header h1 { margin: 0; font-size: 22px; letter-spacing: 0.5px; }
            .content { padding: 30px; }
            h2 { font-size: 20px; margin-top: 0; color: #111827; }
            .credentials { background-color: #f9fafb; border-left: 4px solid #1e3a8a; padding: 20px; border-radius: 4px; margin-top: 25px; }
            .item { margin: 12px 0; }
            .label { font-weight: bold; color: #111827; }
            .value { margin-left: 5px; font-family: 'Courier New', monospace; background-color: #e5e7eb; padding: 5px 8px; border-radius: 4px; }
            .note { background-color: #fff7ed; border-left: 4px solid #d97706; padding: 15px; border-radius: 4px; margin-top: 25px; color: #4b5563; }
            .link { color: #1e3a8a; text-decoration: none; font-weight: bold; }
            .footer { text-align: center; font-size: 12px; color: #6b7280; padding: 25px; background-color: #f9fafb; margin-top: 20px; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1>IMMO360 — Création de votre compte</h1>
            </div>

            <div class="content">
              <h2>Bonjour ${firstName} ${lastName},</h2>
              <p>
                Votre compte IMMO360 a été créé avec succès.
                Voici vos identifiants de connexion :
              </p>

              <div class="credentials">
                <div class="item"><span class="label">Mot de passe temporaire :</span> <span class="value">${plainPassword}</span></div>
                <div class="item"><span class="label">Rôle :</span> <span class="value">${role}</span></div>
              </div>

              <div class="note">
                Veuillez conserver ces informations en lieu sûr.
                Vous devrez vérifier votre adresse email avant votre première connexion.
              </div>

              <p style="margin-top:25px;">
                Accéder à IMMO360 :
                <a class="link" href="${this.configService.get<string>('FRONTEND_URL')}/login">
                  Connexion
                </a>
              </p>
            </div>

            <div class="footer">
              IMMO360 — Gestion Intelligente des Infrastructures<br />
              Ce message a été généré automatiquement.
            </div>
          </div>
        </body>
      </html>
    `;
  }
}
